### ISSUE TITLE
V1.3.0 Crash with WDM

### ISSUE THREAD

**Issue by RedRafe** [raiguard/EvenDistributionLite#11]
### Info
Running EDLite + Warp Drive Machine mod (+ few QoLs mods) on a multiplayer server. WDM mod can be particularly nasty cuz it hops between surfaces.

# Description:

```
115960.155 Error MainLoop.cpp:1391: Exception at tick 2742909: The mod Even Distribution Lite (1.3.0) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event EvenDistributionLite::on_player_fast_transferred (ID 132)
__EvenDistributionLite__/control.lua:275: table index is nil
stack traceback:
__EvenDistributionLite__/control.lua:275: in function <__EvenDistributionLite__/control.lua:161>
115960.155 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Even Distribution Lite (1.3.0) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event EvenDistributionLite::on_player_fast_transferred (ID 132)
__EvenDistributionLite__/control.lua:275: table index is nil
stack traceback:
__EvenDistributionLite__/control.lua:275: in function <__EvenDistributionLite__/control.lua:161>"
```

# Reproduce
We are not aware of what particular action caused the crash to reproduce it, as it is probably a very edge case. We did switch from Even Distribution to Even Distribution Lite because the former had frequent crashes, and this server has been running for 80+ hours with EDLite without any issues before.

**Comment by raiguard** [comment]
Which entity did you hover over to make this crash happen? The entity doesn't have a unit number...

**Comment by RedRafe** [comment]
I'd say probably a gun turret

**Comment by raiguard** [comment]
Gun turrets should always have a unit number.

If you encounter this crash again please let me know, because at the moment I have no idea how this could possibly happen.
