### ISSUE TITLE
Distributing seems to reset hp of science packs (aka cheating in small extra amounts)

### ISSUE THREAD

**Issue by Xetaxheb** [raiguard/EvenDistributionLite#13]
### Description

Cannot and will not test this further but it seems (using basic K2 mod + required asset pack only, even distribution lite, various others but nothing that should be relevant) ctrl+left click dragging the tech cards (renamed science packs) across labs resets the card stacks inside the labs HP to 100%, in other words "cheating in" some extra value. 
I have "swap distribution actions" *checked* and the other two default.
Was very confused why I was getting leftover cards when having exact values 😂

### Reproduction

Install even distribution lite
Ctrl+click for "even distribute mode" (right normal, left inverted) across labs with science packs (either partially used in lab or damaged on cursor)
Open lab to see that science pack hp has reset to 100

**Comment by raiguard** [comment]
Yeah, this is due to the way the mod fundamentally works, I need to rewrite it.
