### ISSUE TITLE
The "Balance Inventories" functionality doesn't exist

### ISSUE THREAD

**Issue by Silver-D** [raiguard/EvenDistributionLite#14]
### Description

The "Balance Inventories" functionality is completely commented out, and thus completely non functional.

In control.lua, everything regarding ``remove_item()`` is commented out, and it doesn't actually balance the items in selected entities.

**Comment by BurntAussieTyre** [comment]
I came here to report the same problem but WTF?!

I guess I'm using the OG mod from 321freddy then!

**Comment by BraveCaperCat2** [comment]
This was apparently "fixed" for specific entities - but it still doesn't work on labs. :(

**Comment by raiguard** [comment]
It works fine for me - please upload exact reproduction steps.

**Comment by raiguard** [comment]
Wow, how on earth did I miss this!? That's a gaping hole.
