### ISSUE TITLE
Typo in per player setting tooltip

### ISSUE THREAD

**Issue by mkaito** [raiguard/EvenDistributionLite#15]
### Description

Tooltip for Per Player setting "swap distribution actions" mentions left click twice instead of left click and right click.

### Reproduction

1. Open settings
2. Mod settings
3. Per Player
4. Even Distribution Lite
5. Observe tooltip on second setting

**Comment by raiguard** [comment]
![image](https://github.com/user-attachments/assets/e5453bba-9246-4223-9038-8fc4595ad283)

It works fine for me. If it's displaying differently for you, that means you messed with the stack transfer keybinds.
