### ISSUE TITLE
NRE on distributing from entities with module slots to entities with inventories (EDL 1.1.0)

### ISSUE THREAD

**Issue by Ocean-Phantom** [raiguard/EvenDistributionLite#4]
### Description

Log of several attempts inducing the error w/ editor extensions
[factorio-previous.log](https://github.com/raiguard/EvenDistributionLite/files/11292541/factorio-previous.log)
Discord links to two videos of reproducing error:
[1](https://cdn.discordapp.com/attachments/1098826967945580686/1098840197673779240Factorio_1.1.81_2023-04-21_13-17-53.mp4)
[2](https://cdn.discordapp.com/attachments/1098826967945580686/1098841666066063440/Untitled.mov)

Reproduced with:
Beacon + spidertron
Assembler + chest
Centrifuge + tank
Refinery + car

neither the player's inventory, the inventory being distributed into, or all module slots in relevant machine appear to need to be filled to capacity.

Does **not** occur for the case where the module being distributed is part of a recipe:
- [Attempting to insert Speed module 2s into an assembler with speed module 1s in its module slots, but with the recipe set for speed module 3s and then also distributing to a spidertron does not induce the error](https://cdn.discordapp.com/attachments/1098826967945580686/1098849618294476830/Factorio_1.1.81_2023-04-21_13-54-22.mp4)

### Reproduction

1. Place lower-tier module in a module slot (eg speed module 1)
2. Completely empty player inventory of all copies of that module
3. Even distribute a higher tier module of the same kind (eg speed 2/3) over the entity with module slots _first_, then distribute to an entity with an inventory in the same pass.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/235276490-749a7d9f-199a-4617-8dce-c67f42629751.png)
Congratulations, you have discovered a Factorio bug! Upgrading modules with fast-transfer doesn't correctly update the hand position. I will fix this in the game.
