### ISSUE TITLE
Request: Hotkey drop

### ISSUE THREAD

**Issue by iamtimsson** [raiguard/EvenDistributionLite#7]
We used to have shift+c  to distribute in an area. Is this against the lite intent of the mod?

**Comment by raiguard** [comment]
Yes, I find shift+c to be way too cheaty. Lite will not have this feature.

**Comment by iamtimsson** [comment]
an option would be nice.
it's like saying i can't wear pants because you don't like to but I also appreciate your effort, knowledge, and response anyway.
love

edit also the logic behind it could be a feat. didn't get in my brain until now

**Comment by raiguard** [comment]
It's my mod, I decide what's in it. I wanted even distribution without all of the bloat and extra features of the original, so that's what I made.

**Comment by iamtimsson** [comment]
well yeah you go ahead don't let anyone tell you what to do bud

**Comment by iamtimsson** [comment]
thanks for the mod

**Comment by wvffle** [comment]
@iamtimsson I came here for the same reason as you although I do not support you. @raiguard is right and if he doesn't want to, he does not need to implement it. If you don't like it, just fork it. It's open source.

**Comment by raiguard** [comment]
This conversation was already over, no need to ping people and provoke further conflict.
