### ISSUE TITLE
Feature: selection tool

### ISSUE THREAD

**Issue by WaterMelonium63** [raiguard/EvenDistributionLite#9]
### Description

Add a selection tool (like the rate calculator one) to distribute items.

Often I find myself:

1. distributing items over thousands of entities, which take several hours
2. distributing items over entites too far apart, for which I have to constantly change the setting `ticks to wait before updating`

This addition (which could be disabled by default) would solve these issues. I understand that this feature may not be in line with Even Distribution Lite's philosophy.

Ps: I tried to make this feature myself but wasn't able to get it done

**Comment by raiguard** [comment]
I think that #8 should solve for your usecases nicely while keeping with the spirit of the mod.

**Comment by WaterMelonium63** [comment]
Thanks! (sorry for the late reply, I've been a little bit busy with life-related stuff)
